name: hauntd-astro
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: hauntd/hauntd-astro
    name: hauntd-astro
